template = "https://github.com/giellalt/template-lang-und"
rev_id = 258
template_sha = "b5271fc37dc1cf0a7448e0553c24b3f857121d34"

[replacements]
__GLOTTOLOG_ID__ = "fare1241"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-gur"
__UND2C__ = "gur"
__UNDEFINED__ = "Farefare"
__UND__ = "gur"
