template = "https://github.com/giellalt/template-lang-und"
rev_id = 261
template_sha = "eaa0621ef7403d653282fabf176060ed3c95ebf4"

[replacements]
__GLOTTOLOG_ID__ = "fare1241"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-gur"
__UND2C__ = "gur"
__UNDEFINED__ = "Farefare"
__UND__ = "gur"
